from enum import StrEnum


class Scope(StrEnum):
    """API token scopes for Remnawave API v3.2.3.

    Mirrors the catalog returned by ``GET /api/tokens/scopes``. Use these members
    when creating API tokens, e.g. ``CreateApiTokenRequestDto(scopes=[Scope.USERS_READ])``.

    Coarse scopes per resource: ``<resource>:*`` (``*_ALL``), ``<resource>:read``,
    ``<resource>:write``. Fine-grained per-endpoint scopes are also available.
    """

    WILDCARD = "*"

    # Users
    USERS_ALL = "users:*"
    USERS_READ = "users:read"
    USERS_WRITE = "users:write"
    USERS_CREATE = "users:create"
    USERS_UPDATE = "users:update"
    USERS_DELETE = "users:delete"
    USERS_LIST = "users:list"
    USERS_STREAM = "users:stream"
    USERS_LIST_TAGS = "users:list-tags"
    USERS_ACCESSIBLE_NODES = "users:accessible-nodes"
    USERS_SUBSCRIPTION_REQUEST_HISTORY = "users:subscription-request-history"
    USERS_BY_SHORT_UUID = "users:by-short-uuid"
    USERS_BY_USERNAME = "users:by-username"
    USERS_BY_ID = "users:by-id"
    USERS_REVOKE_SUBSCRIPTION = "users:revoke-subscription"
    USERS_DISABLE = "users:disable"
    USERS_ENABLE = "users:enable"
    USERS_RESET_TRAFFIC = "users:reset-traffic"
    USERS_EXTEND_EXPIRATION_DATE = "users:extend-expiration-date"
    USERS_RESOLVE = "users:resolve"
    USERS_BULK_DELETE_BY_STATUS = "users:bulk-delete-by-status"
    USERS_BULK_DELETE = "users:bulk-delete"
    USERS_BULK_REVOKE_SUBSCRIPTION = "users:bulk-revoke-subscription"
    USERS_BULK_RESET_TRAFFIC = "users:bulk-reset-traffic"
    USERS_BULK_UPDATE_USERS = "users:bulk-update-users"
    USERS_BULK_UPDATE_SQUADS = "users:bulk-update-squads"
    USERS_BULK_EXTEND_EXPIRATION_DATE = "users:bulk-extend-expiration-date"
    USERS_BULK_ALL_UPDATE_USERS = "users:bulk-all-update-users"
    USERS_BULK_ALL_RESET_TRAFFIC = "users:bulk-all-reset-traffic"
    USERS_BULK_ALL_EXTEND_EXPIRATION_DATE = "users:bulk-all-extend-expiration-date"

    # Hwid User Devices
    HWID_USER_DEVICES_ALL = "hwid-user-devices:*"
    HWID_USER_DEVICES_READ = "hwid-user-devices:read"
    HWID_USER_DEVICES_WRITE = "hwid-user-devices:write"
    HWID_USER_DEVICES_LIST = "hwid-user-devices:list"
    HWID_USER_DEVICES_CREATE = "hwid-user-devices:create"
    HWID_USER_DEVICES_DELETE = "hwid-user-devices:delete"
    HWID_USER_DEVICES_DELETE_ALL = "hwid-user-devices:delete-all"
    HWID_USER_DEVICES_STATS = "hwid-user-devices:stats"
    HWID_USER_DEVICES_TOP_USERS = "hwid-user-devices:top-users"
    HWID_USER_DEVICES_LIST_BY_USER = "hwid-user-devices:list-by-user"

    # Subscriptions
    SUBSCRIPTIONS_ALL = "subscriptions:*"
    SUBSCRIPTIONS_READ = "subscriptions:read"
    SUBSCRIPTIONS_WRITE = "subscriptions:write"
    SUBSCRIPTIONS_LIST = "subscriptions:list"
    SUBSCRIPTIONS_BY_USERNAME = "subscriptions:by-username"
    SUBSCRIPTIONS_BY_SHORT_UUID_PROTECTED = "subscriptions:by-short-uuid-protected"
    SUBSCRIPTIONS_BY_ID = "subscriptions:by-id"
    SUBSCRIPTIONS_RAW = "subscriptions:raw"
    SUBSCRIPTIONS_SUBPAGE_CONFIG = "subscriptions:subpage-config"
    SUBSCRIPTIONS_CONNECTION_KEYS = "subscriptions:connection-keys"

    # Nodes
    NODES_ALL = "nodes:*"
    NODES_READ = "nodes:read"
    NODES_WRITE = "nodes:write"
    NODES_LIST_TAGS = "nodes:list-tags"
    NODES_CREATE = "nodes:create"
    NODES_LIST = "nodes:list"
    NODES_GET = "nodes:get"
    NODES_ENABLE = "nodes:enable"
    NODES_DISABLE = "nodes:disable"
    NODES_DELETE = "nodes:delete"
    NODES_UPDATE = "nodes:update"
    NODES_RESTART = "nodes:restart"
    NODES_RESET_TRAFFIC = "nodes:reset-traffic"
    NODES_RESTART_ALL = "nodes:restart-all"
    NODES_REORDER = "nodes:reorder"
    NODES_BULK_PROFILE_MODIFICATION = "nodes:bulk-profile-modification"
    NODES_BULK_ACTIONS = "nodes:bulk-actions"
    NODES_BULK_UPDATE = "nodes:bulk-update"

    # Node Plugins
    NODE_PLUGINS_ALL = "node-plugins:*"
    NODE_PLUGINS_READ = "node-plugins:read"
    NODE_PLUGINS_WRITE = "node-plugins:write"
    NODE_PLUGINS_TORRENT_BLOCKER_REPORTS = "node-plugins:torrent-blocker-reports"
    NODE_PLUGINS_TORRENT_BLOCKER_STATS = "node-plugins:torrent-blocker-stats"
    NODE_PLUGINS_TRUNCATE = "node-plugins:truncate"
    NODE_PLUGINS_LIST = "node-plugins:list"
    NODE_PLUGINS_GET = "node-plugins:get"
    NODE_PLUGINS_UPDATE = "node-plugins:update"
    NODE_PLUGINS_DELETE = "node-plugins:delete"
    NODE_PLUGINS_CREATE = "node-plugins:create"
    NODE_PLUGINS_REORDER = "node-plugins:reorder"
    NODE_PLUGINS_CLONE = "node-plugins:clone"
    NODE_PLUGINS_EXECUTOR = "node-plugins:executor"

    # Bandwidth Stats
    BANDWIDTH_STATS_ALL = "bandwidth-stats:*"
    BANDWIDTH_STATS_READ = "bandwidth-stats:read"
    BANDWIDTH_STATS_WRITE = "bandwidth-stats:write"
    BANDWIDTH_STATS_NODE_USERS_USAGE = "bandwidth-stats:node-users-usage"
    BANDWIDTH_STATS_NODES_USERS_USAGE = "bandwidth-stats:nodes-users-usage"
    BANDWIDTH_STATS_USER_USAGE = "bandwidth-stats:user-usage"
    BANDWIDTH_STATS_NODES_USAGE = "bandwidth-stats:nodes-usage"
    BANDWIDTH_STATS_NODE_USAGE = "bandwidth-stats:node-usage"
    BANDWIDTH_STATS_INTERNAL_SQUAD_USAGE = "bandwidth-stats:internal-squad-usage"
    BANDWIDTH_STATS_INTERNAL_SQUAD_USER_USAGE = (
        "bandwidth-stats:internal-squad-user-usage"
    )

    # Connections (replaces Ip Control in v3.x)
    CONNECTIONS_ALL = "connections:*"
    CONNECTIONS_READ = "connections:read"
    CONNECTIONS_WRITE = "connections:write"
    CONNECTIONS_BY_USER = "connections:by-user"
    CONNECTIONS_BY_USER_RESULT = "connections:by-user-result"
    CONNECTIONS_BY_NODE = "connections:by-node"
    CONNECTIONS_BY_NODE_RESULT = "connections:by-node-result"
    CONNECTIONS_DROP = "connections:drop"

    # Config Profiles
    CONFIG_PROFILES_ALL = "config-profiles:*"
    CONFIG_PROFILES_READ = "config-profiles:read"
    CONFIG_PROFILES_WRITE = "config-profiles:write"
    CONFIG_PROFILES_LIST = "config-profiles:list"
    CONFIG_PROFILES_LIST_INBOUNDS = "config-profiles:list-inbounds"
    CONFIG_PROFILES_LIST_PROFILE_INBOUNDS = "config-profiles:list-profile-inbounds"
    CONFIG_PROFILES_GET = "config-profiles:get"
    CONFIG_PROFILES_GET_COMPUTED = "config-profiles:get-computed"
    CONFIG_PROFILES_DELETE = "config-profiles:delete"
    CONFIG_PROFILES_CREATE = "config-profiles:create"
    CONFIG_PROFILES_UPDATE = "config-profiles:update"
    CONFIG_PROFILES_REORDER = "config-profiles:reorder"

    # Internal Squads
    INTERNAL_SQUADS_ALL = "internal-squads:*"
    INTERNAL_SQUADS_READ = "internal-squads:read"
    INTERNAL_SQUADS_WRITE = "internal-squads:write"
    INTERNAL_SQUADS_LIST = "internal-squads:list"
    INTERNAL_SQUADS_GET = "internal-squads:get"
    INTERNAL_SQUADS_CREATE = "internal-squads:create"
    INTERNAL_SQUADS_ACCESSIBLE_NODES = "internal-squads:accessible-nodes"
    INTERNAL_SQUADS_UPDATE = "internal-squads:update"
    INTERNAL_SQUADS_DELETE = "internal-squads:delete"
    INTERNAL_SQUADS_ADD_USERS = "internal-squads:add-users"
    INTERNAL_SQUADS_REMOVE_USERS = "internal-squads:remove-users"
    INTERNAL_SQUADS_REORDER = "internal-squads:reorder"

    # External Squads
    EXTERNAL_SQUADS_ALL = "external-squads:*"
    EXTERNAL_SQUADS_READ = "external-squads:read"
    EXTERNAL_SQUADS_WRITE = "external-squads:write"
    EXTERNAL_SQUADS_LIST = "external-squads:list"
    EXTERNAL_SQUADS_GET = "external-squads:get"
    EXTERNAL_SQUADS_CREATE = "external-squads:create"
    EXTERNAL_SQUADS_UPDATE = "external-squads:update"
    EXTERNAL_SQUADS_DELETE = "external-squads:delete"
    EXTERNAL_SQUADS_ADD_USERS = "external-squads:add-users"
    EXTERNAL_SQUADS_REMOVE_USERS = "external-squads:remove-users"
    EXTERNAL_SQUADS_REORDER = "external-squads:reorder"

    # Hosts
    HOSTS_ALL = "hosts:*"
    HOSTS_READ = "hosts:read"
    HOSTS_WRITE = "hosts:write"
    HOSTS_LIST_TAGS = "hosts:list-tags"
    HOSTS_CREATE = "hosts:create"
    HOSTS_UPDATE = "hosts:update"
    HOSTS_LIST = "hosts:list"
    HOSTS_GET = "hosts:get"
    HOSTS_REORDER = "hosts:reorder"
    HOSTS_DELETE = "hosts:delete"
    HOSTS_BULK_DELETE = "hosts:bulk-delete"
    HOSTS_BULK_DISABLE = "hosts:bulk-disable"
    HOSTS_BULK_ENABLE = "hosts:bulk-enable"
    HOSTS_BULK_UPDATE = "hosts:bulk-update"

    # Subscription Template
    SUBSCRIPTION_TEMPLATE_ALL = "subscription-template:*"
    SUBSCRIPTION_TEMPLATE_READ = "subscription-template:read"
    SUBSCRIPTION_TEMPLATE_WRITE = "subscription-template:write"
    SUBSCRIPTION_TEMPLATE_LIST = "subscription-template:list"
    SUBSCRIPTION_TEMPLATE_GET = "subscription-template:get"
    SUBSCRIPTION_TEMPLATE_UPDATE = "subscription-template:update"
    SUBSCRIPTION_TEMPLATE_DELETE = "subscription-template:delete"
    SUBSCRIPTION_TEMPLATE_CREATE = "subscription-template:create"
    SUBSCRIPTION_TEMPLATE_REORDER = "subscription-template:reorder"

    # Subscription Settings
    SUBSCRIPTION_SETTINGS_ALL = "subscription-settings:*"
    SUBSCRIPTION_SETTINGS_READ = "subscription-settings:read"
    SUBSCRIPTION_SETTINGS_WRITE = "subscription-settings:write"
    SUBSCRIPTION_SETTINGS_GET = "subscription-settings:get"
    SUBSCRIPTION_SETTINGS_UPDATE = "subscription-settings:update"

    # Infra Billing
    INFRA_BILLING_ALL = "infra-billing:*"
    INFRA_BILLING_READ = "infra-billing:read"
    INFRA_BILLING_WRITE = "infra-billing:write"
    INFRA_BILLING_LIST_PROVIDERS = "infra-billing:list-providers"
    INFRA_BILLING_GET_PROVIDER = "infra-billing:get-provider"
    INFRA_BILLING_DELETE_PROVIDER = "infra-billing:delete-provider"
    INFRA_BILLING_CREATE_PROVIDER = "infra-billing:create-provider"
    INFRA_BILLING_UPDATE_PROVIDER = "infra-billing:update-provider"
    INFRA_BILLING_CREATE_BILL_RECORD = "infra-billing:create-bill-record"
    INFRA_BILLING_LIST_BILL_RECORDS = "infra-billing:list-bill-records"
    INFRA_BILLING_DELETE_BILL_RECORD = "infra-billing:delete-bill-record"
    INFRA_BILLING_LIST_BILLING_NODES = "infra-billing:list-billing-nodes"
    INFRA_BILLING_UPDATE_BILLING_NODE = "infra-billing:update-billing-node"
    INFRA_BILLING_CREATE_BILLING_NODE = "infra-billing:create-billing-node"
    INFRA_BILLING_DELETE_BILLING_NODE = "infra-billing:delete-billing-node"

    # System
    SYSTEM_ALL = "system:*"
    SYSTEM_READ = "system:read"
    SYSTEM_WRITE = "system:write"
    SYSTEM_METADATA = "system:metadata"
    SYSTEM_STATS = "system:stats"
    SYSTEM_BANDWIDTH_STATS = "system:bandwidth-stats"
    SYSTEM_NODES_STATISTICS = "system:nodes-statistics"
    SYSTEM_REMNAWAVE_HEALTH = "system:remnawave-health"
    SYSTEM_NODES_METRICS = "system:nodes-metrics"
    SYSTEM_GENERATE_X25519 = "system:generate-x25519"
    SYSTEM_TEST_SRR_MATCHER = "system:test-srr-matcher"
    SYSTEM_RECAP = "system:recap"
    SYSTEM_CONFIGURATION = "system:configuration"
    SYSTEM_STATS_DIGEST = "system:stats-digest"
    SYSTEM_HTTP_STATS = "system:http-stats"

    # Keygen
    KEYGEN_ALL = "keygen:*"
    KEYGEN_READ = "keygen:read"
    KEYGEN_WRITE = "keygen:write"
    KEYGEN_GET = "keygen:get"

    # Subscription Request History
    SUBSCRIPTION_REQUEST_HISTORY_ALL = "subscription-request-history:*"
    SUBSCRIPTION_REQUEST_HISTORY_READ = "subscription-request-history:read"
    SUBSCRIPTION_REQUEST_HISTORY_WRITE = "subscription-request-history:write"
    SUBSCRIPTION_REQUEST_HISTORY_LIST = "subscription-request-history:list"
    SUBSCRIPTION_REQUEST_HISTORY_STATS = "subscription-request-history:stats"

    # Snippets
    SNIPPETS_ALL = "snippets:*"
    SNIPPETS_READ = "snippets:read"
    SNIPPETS_WRITE = "snippets:write"
    SNIPPETS_LIST = "snippets:list"
    SNIPPETS_DELETE = "snippets:delete"
    SNIPPETS_CREATE = "snippets:create"
    SNIPPETS_UPDATE = "snippets:update"
    SNIPPETS_SYNC = "snippets:sync"

    # Subscription Page Configs
    SUBSCRIPTION_PAGE_CONFIGS_ALL = "subscription-page-configs:*"
    SUBSCRIPTION_PAGE_CONFIGS_READ = "subscription-page-configs:read"
    SUBSCRIPTION_PAGE_CONFIGS_WRITE = "subscription-page-configs:write"
    SUBSCRIPTION_PAGE_CONFIGS_LIST = "subscription-page-configs:list"
    SUBSCRIPTION_PAGE_CONFIGS_GET = "subscription-page-configs:get"
    SUBSCRIPTION_PAGE_CONFIGS_UPDATE = "subscription-page-configs:update"
    SUBSCRIPTION_PAGE_CONFIGS_DELETE = "subscription-page-configs:delete"
    SUBSCRIPTION_PAGE_CONFIGS_CREATE = "subscription-page-configs:create"
    SUBSCRIPTION_PAGE_CONFIGS_REORDER = "subscription-page-configs:reorder"
    SUBSCRIPTION_PAGE_CONFIGS_CLONE = "subscription-page-configs:clone"

    # Metadata
    METADATA_ALL = "metadata:*"
    METADATA_READ = "metadata:read"
    METADATA_WRITE = "metadata:write"
    METADATA_GET_USER = "metadata:get-user"
    METADATA_UPSERT_USER = "metadata:upsert-user"
    METADATA_GET_NODE = "metadata:get-node"
    METADATA_UPSERT_NODE = "metadata:upsert-node"
